# Generated by Django 2.1.7 on 2019-03-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='other_vehicle_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('staff_to_contact', models.CharField(max_length=20)),
                ('staff_phone_number', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('entrance_date', models.DateField()),
                ('entrance_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='other_vehicle_exit_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exit_time', models.TimeField()),
                ('receipt_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='security.other_vehicle_entry_table')),
            ],
        ),
        migrations.CreateModel(
            name='staff_vehicle_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('staff_type', models.CharField(choices=[('Regular', 'Regular'), ('Guest', 'Guest')], default='Regular', max_length=10)),
                ('staff_to_contact', models.CharField(blank=True, max_length=20)),
                ('staff_phone_number', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('entrance_date', models.DateField()),
                ('entrance_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='staff_vehicle_exit_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exit_time', models.TimeField()),
                ('receipt_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='security.staff_vehicle_entry_table')),
            ],
        ),
        migrations.CreateModel(
            name='Users_table',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='visitor_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=10)),
                ('staff_to_contact', models.CharField(max_length=20)),
                ('staff_phone_number', models.CharField(max_length=10)),
                ('purpose', models.CharField(max_length=200)),
                ('entrance_date', models.DateField()),
                ('entrance_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Users_table')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_exit_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('exit_time', models.TimeField()),
                ('receipt_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='security.visitor_entry_table')),
            ],
        ),
        migrations.AddField(
            model_name='staff_vehicle_entry_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Users_table'),
        ),
        migrations.AddField(
            model_name='other_vehicle_entry_table',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.Users_table'),
        ),
    ]
