# Generated by Django 2.1.7 on 2019-03-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_vehicle_exit_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='staff_vehicle_exit_table',
            name='receipt_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='security.staff_vehicle_entry_table'),
        ),
    ]
