# Generated by Django 2.1.7 on 2019-03-25 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20190326_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='other_vehicle_exit_table',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitor_exit_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='other_vehicle_exit_table',
            name='receipt_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='security.other_vehicle_entry_table'),
        ),
        migrations.AlterField(
            model_name='visitor_exit_table',
            name='receipt_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='security.visitor_entry_table'),
        ),
    ]
